server:
  port: 9090
  servlet:
    context-path: /javabackend


spring:
  application:
    name: javabackend
  datasource:
    url: jdbc:postgresql://postgres-db.clm0ia6w8t9k.ap-southeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: EdeepeepE12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        daialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect